project:
  type: website
  resources:
    - CNAME

website:
  title: "Sadman's Blog"
  description: "A data science blog by Sadman Hossain"
  site-url: https://sadman.ca
  repo-url: https://github.com/sadmanca/blog
  twitter-card:
    creator: "@sadmanca"
    card-style: summary_large_image
  navbar:
    title: Sadman's Blog
    background: "#eee"
    logo: "images/blog-logo.png"
    collapse-below: lg
    left:
      - href: index.xml
        text: "{{< fa square-rss >}} RSS"
    right:
      - href: about.qmd
        text: "{{< fa circle-user >}} About Me"
      - icon: github
        href: https://github.com/sadmanca/blog
      - icon: twitter
        href: https://twitter.com/sadmanca
  page-footer:
    center:
      - href: https://sadman.ca
        text: sadman.ca
  search:
    location: navbar
    type: textbox
format:
  html:
    theme:
      light:
        # - cosmos
        - ember.scss
      dark:
        - darkly
        - ember.scss
    css: styles.css