project:
  type: website
  resources:
    - CNAME

execute:
  freeze: true
website:
  title: "Sadman's Blog"
  description: "A data science blog by Sadman Hossain"
  site-url: https://sadman.ca
  repo-url: https://github.com/sadmanca/blog
  twitter-card:
    creator: "@sadmanca"
    card-style: summary_large_image
  navbar:
    title: Sadman's Blog
    background: "#eeee"
    logo: "images/blog-logo.svg"
    collapse-below: lg
    left:
      - href: index.xml
        text: "{{< fa square-rss >}} RSS"
    right:
      - href: about.qmd
        text: "{{< fa circle-user >}} About"
      - icon: github
        href:  https://github.com/sadmanca/blog
      - icon: twitter
        href: https://twitter.com/sadmanca
  page-footer:
    center:
      - href: https://sadman.ca
        text: sadman.ca
  search:
    location: navbar
    type: textbox
format:
  html:
    theme: ember.scss
    css: styles.css