on:
  workflow_dispatch:

name: Quarto Render and Publish (dev)

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      
      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: dev-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
